name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run notebooks (smoke test)
      run: |
        python -c "import matplotlib; matplotlib.use('Agg')"
        pip install nbconvert ipywidgets
        jupyter nbconvert --to notebook --execute notebooks/*.ipynb --output-dir=out
